---
# The port that the server will listen to.
port: 5042

# The secret that will be used for the deployment.
secret: "42"

# The tls configuration.
tlsconfig:
  # The path to the public key.
  public_key_path: "cert.pem"
  # The path to the private key.
  private_key_path: "key.pem"

# The list of deployments that will be checked.
deployments:
  - deployment:
      user: klipitkas
      repository: git@github.com:klipitkas/remove_greek_accents.git
      branch: master
      path: /home/klipitkas/test
      before_script: /home/klipitkas/jwt-go/before.sh
      after_script: /home/klipitkas/jwt-go/after.sh
