port: 5042
deployments:
    - repository: git@github.com:klipitkas/hooktail.git
      secret: very-sensitive
      user: klipitkas
      branch: master
      path: /home/klipitkas/hooktail
      before_script: /home/klipitkas/hooktail/before.sh
      after_script: /home/klipitkas/hooktail/after.sh
